import type { Tutor, TutorDetails } from '@/types/tutor';

export const mockTutors: Tutor[] = [
  {
    id: 1,
    user_id: 101,
    first_name: 'Алексей',
    last_name: 'Иванов',
    photo_url: '',
    bio: 'Выпускник ФПМИ МФТИ. Специализируюсь на подготовке к ЕГЭ по математике и олимпиадам. Имею опыт преподавания более 5 лет.',
    education: 'МФТИ, ФПМИ, 2018',
    faculty: 'ФПМИ',
    graduation_year: 2018,
    experience_years: 5,
    price_per_hour: 2000,
    format: 'BOTH',
    city: 'Москва',
    avg_rating: 4.8,
    reviews_count: 24,
    status: 'APPROVED',
    created_at: '2023-01-15T10:00:00Z',
    updated_at: '2023-11-20T15:30:00Z',
  },
  {
    id: 2,
    user_id: 102,
    first_name: 'Мария',
    last_name: 'Петрова',
    photo_url: '',
    bio: 'Студентка 4 курса ФРКТ. Помогу подготовиться к ЕГЭ и ОГЭ по физике. Объясняю сложные темы простым языком.',
    education: 'МФТИ, ФРКТ, 2024',
    faculty: 'ФРКТ',
    graduation_year: 2024,
    experience_years: 3,
    price_per_hour: 1500,
    format: 'ONLINE',
    avg_rating: 4.9,
    reviews_count: 18,
    status: 'APPROVED',
    created_at: '2023-03-10T12:00:00Z',
    updated_at: '2023-11-18T09:15:00Z',
  },
  {
    id: 3,
    user_id: 103,
    first_name: 'Дмитрий',
    last_name: 'Сидоров',
    photo_url: '',
    bio: 'Преподаватель информатики и программирования. Готовлю к олимпиадам и поступлению в технические вузы.',
    education: 'МФТИ, ФИВТ, 2015',
    faculty: 'ФИВТ',
    graduation_year: 2015,
    experience_years: 8,
    price_per_hour: 2500,
    format: 'BOTH',
    city: 'Москва',
    avg_rating: 5.0,
    reviews_count: 42,
    status: 'APPROVED',
    created_at: '2022-09-01T08:00:00Z',
    updated_at: '2023-11-25T14:00:00Z',
  },
  {
    id: 4,
    user_id: 104,
    first_name: 'Екатерина',
    last_name: 'Смирнова',
    photo_url: '',
    bio: 'Магистрант ФОПФ. Преподаю физику для школьников и студентов. Индивидуальный подход к каждому ученику.',
    education: 'МФТИ, ФОПФ, 2020',
    faculty: 'ФОПФ',
    graduation_year: 2020,
    experience_years: 4,
    price_per_hour: 1800,
    format: 'ONLINE',
    avg_rating: 4.7,
    reviews_count: 15,
    status: 'APPROVED',
    created_at: '2023-02-20T11:30:00Z',
    updated_at: '2023-11-22T16:45:00Z',
  },
];

export const mockTutorDetails: Record<number, TutorDetails> = {
  1: {
    ...mockTutors[0],
    subjects: [
      { subject_id: 1, subject_name: 'Математика' },
      { subject_id: 2, subject_name: 'Физика' },
    ],
    levels: [
      { level_code: 'ege', level_name: 'ЕГЭ' },
      { level_code: 'olymp', level_name: 'Олимпиады' },
    ],
  },
  2: {
    ...mockTutors[1],
    subjects: [{ subject_id: 2, subject_name: 'Физика' }],
    levels: [
      { level_code: 'ege', level_name: 'ЕГЭ' },
      { level_code: 'oge', level_name: 'ОГЭ' },
    ],
  },
  3: {
    ...mockTutors[2],
    subjects: [{ subject_id: 3, subject_name: 'Информатика' }],
    levels: [
      { level_code: 'olymp', level_name: 'Олимпиады' },
      { level_code: 'university', level_name: 'Университет' },
    ],
  },
  4: {
    ...mockTutors[3],
    subjects: [{ subject_id: 2, subject_name: 'Физика' }],
    levels: [
      { level_code: 'ege', level_name: 'ЕГЭ' },
      { level_code: 'school', level_name: 'Школа' },
    ],
  },
};
